package org.bungeni.exist.tools.backupconverter;


import java.io.File;
import java.io.IOException;
import java.util.Properties;

import org.exist.EXistException;
import org.exist.storage.ConsistencyCheckTask;
import org.exist.storage.DBBroker;
import org.exist.storage.SystemTask;
import org.exist.util.Configuration;

/**
 * Schedulable System Task for eXist which
 * will backup the database and create an
 * Akoma Ntoso Layout mirroring the database
 *
 * This task may be scheduled via. conf.xml or
 * the XQuery function system:trigger-system-task
 *
 * Parameters for this task are as follows -
 *
 *  <parameters>
 *      <param name="eXist.backup.location" value="/eXist-backups"/>
 *      <param name="incremental" value="no"/>
 *      <param name="an.destination" value="yes"/>
 *  </parameters>
 *
 * eXist.backup.location - This is the filesystem location
 * for storing backups of the eXist database. These backups
 * are generated by this tool and needed as an intermediatory
 * step before conversion to the Akoma Ntoso format takes place.
 *
 * incremental - Should we make use of incremental eXist
 * backups and just convert the changes of the database
 * over to the destination.
 *
 * an.destination - This is the filesystem location for
 * writting the fully expanded Akoma Ntoso layout of the
 * database to.
 *
 * @author Adam Retter <adam.retter@googlemail.com>
 * @version 1.0
 */
public class ANMirrorTask implements SystemTask
{
    private String existBackupLocation = null;
    private boolean incremental = false;
    private File anDestination = null;

    private ConsistencyCheckTask consistencyCheckTask = null;

    public final static String EXIST_BACKUP_LOCATION_PROP_NAME = "eXist.backup.location";
    public final static String INCREMENTAL_PROP_NAME = "incremental";
    public final static String AN_DESTINATION_PROP_NAME = "an.destination";

    /**
     * @see org.exist.storage.SystemTask#configure(org.exist.util.Configuration, java.util.Properties)
     */
    @Override
    public void configure(Configuration config, Properties properties) throws EXistException
    {
        existBackupLocation = properties.getProperty(EXIST_BACKUP_LOCATION_PROP_NAME, "/tmp");
        String incr = properties.getProperty(INCREMENTAL_PROP_NAME, "false").toUpperCase();
        incremental = (incr.equals("TRUE") || incr.equals("YES"));
        anDestination = new File(properties.getProperty(AN_DESTINATION_PROP_NAME, "/tmp/an"));

        //setup the consistencyCheckTask
        Properties consistencyCheckTaskProperties = new Properties();

        consistencyCheckTaskProperties.put(ConsistencyCheckTask.OUTPUT_PROP_NAME, existBackupLocation);
        consistencyCheckTaskProperties.put(ConsistencyCheckTask.BACKUP_PROP_NAME, "yes");
        consistencyCheckTaskProperties.put(ConsistencyCheckTask.INCREMENTAL_PROP_NAME, incremental ? "yes" : "no");

        this.consistencyCheckTask = new ConsistencyCheckTask();
        
    }

    /**
     * @see org.exist.storage.SystemTask#execute(org.exist.storage.DBBroker)
     */
    @Override
    public void execute(DBBroker broker) throws EXistException
    {
        //run the consistency checker first to generate the backup
        consistencyCheckTask.execute(broker);

        try
        {
            //get the backup details
            File backupSrc = consistencyCheckTask.getLastExportedBackup();

            //convert the backup to the mirror
            BackupConverter backupConverter = new BackupConverter();
            backupConverter.convert(backupSrc, anDestination);
        }
        catch(IOException ioe)
        {
            throw new EXistException(ioe.getMessage(), ioe);
        }
    }
}
